name=RingFileLogger
version=0.1.0
author=Al-Zhilin <alekseyzh5@gmail.com>
maintainer=Al-Zhilin <alekseyzh6@gmail.com>
sentence=Organizes circular log storage in the form of files.
paragraph=The library allows you to create a circular file-based log storage on any data storage medium.
category=Data Storage
url=https://github.com/Al-Zhilin/RingFileLogger
architectures=esp32